import Head from 'next/head'
import Layout from '@/components/layout';
import Flickity from 'react-flickity-component' 

const flickityOptions = {
    initialIndex: 1
}

function Carousel() {
    return (
      <Flickity
        className={'carousel'} // default ''
        elementType={'div'} // default 'div'
        options={flickityOptions} // takes flickity options {}
        disableImagesLoaded={false} // default false
        reloadOnUpdate // default false
        static // default false 
      >
        <img src="/assets/images/banner/banner2.webp" />
        <img src="/assets/images/banner/banner1.webp" />
        <img src="/assets/images/banner/banner2.webp" />
        <img src="/assets/images/banner/banner1.webp" />
      </Flickity>
    );
  }

export default function Home() {
    return (
        <>
            <Head>
                <title>Home Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout> 

            <Carousel />
                <p>body data</p>
            </Layout>

        </>
    )
}
